version: "3.8"
services: 
  app:
    build: .
    ports:
      - "8000:8000"
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret 
    ports:
      - "5432:5432"  
