apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: task-api 
spec: 
  replicas: 2
  selector:
    matchLabels:
      app: task-api
  template:
    metadata:
      labels:
        app: task-api
    spec: 
      containers:
        - name: task-api
          image: task-url/task-api:latest 
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /health
              port: 8000 
            initialDelaySeconds: 5 
            periodSeconds: 10  
