apiVersion: v1 
kind: ConfigMap
metadata: 
  name: prometheus-config 
data:
  prometheus.yml: | 
    global:
      scrape_interval: 15s
    scrape_interval: 
      - job_name: 'task-api'
        static_configs:
          - targets: ['task-api-service:8000']    
